apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
spec:
  selector:
    matchLabels:
      k8s-app: default-http-backend
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
        terminationGracePeriodSeconds: 60
        containers:
          - name: default-http-backend
          # 如果是/就返回404页面，如果是/healthz返回200
            image: gcr.io/google_containers/defaultbackend:1.0
            livenessProbe:
              httpGet:
                port: 8080
                path: /healthz
                scheme: HTTP
              initialDelaySeconds: 30
              timeoutSeconds: 5
            ports:
              - containerPort: 8080
            resources:
              limits:
                cpu: 10m
                memory: 20Mi
              requests:
                cpu: 10m
                memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: kube-system
  labels:
    k8s-app: default-http-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    k8s-app: default-http-backend
