apiVersion: v1
kind: Service
metadata:
  name: front-svr
  labels:
    app: nginx
    tier: fronted
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx
    tier: fronted
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: fronted
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: fronted
    spec:
      containers:
        - name: nginx-app
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html     #pod内部路径
              name: html
              readOnly: true
            - mountPath: /tmp
              name: tmp
      restartPolicy: "Never"
      volumes:
        - name: html
          hostPath:
            path: /tmp/html
            type: Directory
        - name: tmp
          hostPath:
            path: /tmp/test