apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webaapp
spec:
  containers:
    - name: webapp
      image: tomcat
      ports:
        - containerPort: 8080
          hostPort: 8081