apiVersion: v1
kind: Pod
metadata:
  namespace: demo-ns
  name: demo-pod
spec:
  containers:
    - name: demo-container
      image: nginx:latest
      ports:
        - containerPort: 80
          name: httpd
          protocol: TCP
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: k1
                operator: In
                values:
                  - v1
          topologyKey: "kubetnetes.io/hostname"

    # 必须调度到带k1=v1标签的pod节点
    # Exist的范围比In大，如果是Exist表示只要带了key:k1的pod都会被选择，此时可以不用填写values