apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: Myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9736
    nodePort: 30061
  clusterIP: 172.19.11.151
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 47.99.225.165
