apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-affinity
  namespace: default
  name: pod-affinity
spec:
  containers:
    - name: my-pod
      image: nginx:1.11.9
      imagePullPolicy: IfNotPresent
  schedulerName: default-scheduler
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: run
              operator: In
              values:
                - "node-affinity"
        topologyKey: kubernetes.io/hostname
