apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: scm
  labels:
    app: demo
spec:
  replicas: 3
  minReadySeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      terminationGracePeriodSeconds: 60 #k8s将会给应用发送SIGTERM信号，可以用来正确、优雅地关闭应用,默认为30秒
      containers:
        - name: dmo
          image: review:0.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8080
              scheme: HTTP
              path: /health
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 500m
              memoryt: 500Mi
          env:
            - name: PROFILE
              value: "test"
          ports:
            - containerPort: 8080
              name: http

